### ISSUE TITLE
Master Password lockout

### ISSUE THREAD

**Issue by tdreger123** [swiftyapp/swifty#14]
**Describe the bug**
I have been locked out of the app because it says that the master password is incorrect. I know that it is not. This has happened before. The other time it happened I restarted the app and it worked. Any suggestions? Could it be due to the new update?

Also, I am new to github but I wanted to know if there is a way to update the swifty app or does it happen automatically when you push new changes?

**Comment by alchaplinsky** [comment]
Hey tdreger123,
Currently, Swifty shows "incorrect password" error when there was any problem while decrypting your data. So it is possible that entered password is correct, but something else went wrong. There was a breaking change in v0.2.0 (due to encryption algorithm change) so if you started using app prior to v0.2.0 and then it was automatically updated that may be the cause of this issue.

**Comment by alchaplinsky** [comment]
So you can try to uninstall current version and then install v0.2.0-beta.3 to check if your password works in it. If it works you might need to migrate your data to newer version.

**Comment by alchaplinsky** [comment]
Closing for now due to lack of activity for more than 45 days
